# Generated by Django 5.0 on 2026-02-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کراول')),
                ('start_date', models.CharField(max_length=20, verbose_name='تاریخ شروع')),
                ('end_date', models.CharField(max_length=20, verbose_name='تاریخ پایان')),
                ('province_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه استان')),
                ('township_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه شهر')),
                ('province_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام استان')),
                ('township_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شهر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('total_records', models.IntegerField(default=0, verbose_name='تعداد کل رکوردها')),
                ('fetched_records', models.IntegerField(default=0, verbose_name='تعداد رکوردهای دریافت شده')),
                ('current_page', models.IntegerField(default=0, verbose_name='صفحه فعلی')),
                ('total_pages', models.IntegerField(default=0, verbose_name='تعداد کل صفحات')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه Task')),
            ],
            options={
                'verbose_name': 'کراول جاب',
                'verbose_name_plural': 'کراول جاب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شماره درخواست')),
                ('applicant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام متقاضی')),
                ('user_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='تصویر کاربر')),
                ('license_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان مجوز')),
                ('organization_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان سازمان')),
                ('province_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('township_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('responded_at', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ پاسخ')),
                ('status_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه وضعیت')),
                ('status_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان وضعیت')),
                ('status_slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slug وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='داده خام')),
                ('crawl_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='jobs.crawljob', verbose_name='کراول جاب')),
            ],
            options={
                'verbose_name': 'رکورد کراول',
                'verbose_name_plural': 'رکوردهای کراول',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['crawl_job', 'request_number'], name='jobs_crawlr_crawl_j_de8074_idx'), models.Index(fields=['created_at'], name='jobs_crawlr_created_e55a8c_idx')],
            },
        ),
    ]
